#!/bin/bash

# chkconfig:   - 85 15
# description: Nginx HTTP Proxy Server

nginx=$(which nginx 2> /dev/null)
nginx=${nginx:-/usr/local/sbin/nginx}
prog=$(basename $nginx)

self=$(readlink -n $0)
self=${self:-$0}
cd $(dirname $self)/../..
path=$(pwd)

logs=logs
pid=logs/nginx.pid
conf=etc/nginx.conf

usage() {
    echo "Usage: $0 [start|stop|restart|configtest]"
}

start() {
    [ -d $logs ] || mkdir $logs
    [ -f $pid ] && stop
    /bin/echo -n "starting $prog ...   "
    $nginx -p $path -c $conf && echo '[OK]' || echo '[NG]'
}

stop() {
    /bin/echo -n "stoping $prog ...    "
    $nginx -p $path -c $conf -s stop && echo '[OK]' || echo '[NG]'
}

restart() {
    stop
    sleep 1
    start
}

configtest() {
    $nginx -p $path -c $conf -t
}

case $1 in
    start|stop|restart|configtest) $1;;
    *) usage;;
esac
